---
- name: Testing out ansible!
  hosts: ub
  become: yes
  become_user: root
  vars_files:
    - secret
  vars:
    ansible_become_password: "{{ sudo_password }}"

  tasks:
    - name: Update cache
      apt: 
        state: latest
